[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python start_server.py"
# healthcheckPath = "/health"
# healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHON_ENV = "production"
SECRET_KEY = "najah-ai-secret-key-super-secure-2024"
JWT_SECRET_KEY = "najah-ai-jwt-secret-key-ultra-secure-2024"
CORS_ORIGINS = "https://localhost:3000,https://vercel.app"

