"""create all missing tables

Revision ID: b94e8b5fa862
Revises: 551950d0ae75
Create Date: 2025-07-18 20:12:41.764256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94e8b5fa862'
down_revision: Union[str, Sequence[str], None] = '551950d0ae75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('categories')
    # op.alter_column('contents', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    # op.alter_column('contents', 'title',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            nullable=False)
    # op.alter_column('contents', 'subject',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            nullable=False)
    # op.alter_column('contents', 'level',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(),
    #            nullable=False)
    # op.drop_constraint(op.f('fk_contents_category_id'), 'contents', type_='foreignkey')
    # op.drop_column('contents', 'category_id')
    # (aucune op.create_table générée, donc rien à faire ici)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('contents', sa.Column('category_id', sa.INTEGER(), nullable=True))
    # op.create_foreign_key(op.f('fk_contents_category_id'), 'contents', 'categories', ['category_id'], ['id'])
    # op.alter_column('contents', 'level',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('contents', 'subject',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('contents', 'title',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('contents', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # op.create_table('categories',
    # sa.Column('id', sa.INTEGER(), nullable=True),
    # sa.Column('name', sa.TEXT(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
