# Modules essentiels pour l'API
from . import auth
from . import users
from . import quizzes
from . import quiz_results
from . import badges
from . import class_groups
from . import contents
from . import learning_paths
from . import learning_history
from . import messages
from . import ai_analytics
from . import student_performance
from . import assessment
from . import recommendations
from . import gamification
from . import advanced_analytics
from . import homework
from . import calendar
from . import collaboration
from . import ai_advanced
from . import reports
from . import activity

# Modules pour les fonctionnalités intelligentes
from . import performance_monitoring
from . import gap_analysis
from . import adaptive_quizzes
from . import cognitive_diagnostic
from . import ai
from . import notifications
from . import notifications_ws
from . import threads
from . import notification_preferences
from . import categories
from . import quiz_json
from . import settings
from . import score_corrections
from . import teacher_messaging
from . import student_messaging
from . import teacher_schedule
from . import auto_correction
from . import remediation
from . import teacher_collaboration
from . import continuous_assessment
from . import export_reports
from . import external_integrations
from . import dashboard_data
from . import student_analytics
from . import notes
from . import forum
from . import organization
from . import library
from . import organization_advanced
from . import teacher_assignments
from . import student_organization_real
from . import notifications_advanced
from . import student_organization
from . import learning_goals
from . import teacher_tasks
from . import progress_tracking
from . import monitoring 